### ISSUE TITLE
Use the "secrets" module, not "random"

### ISSUE THREAD

**Issue by runxiyu** [ZigaoWang/password-generator#1]
> **Warning**
> The pseudo-random generators of this module should not be used for security purposes. For security or cryptographic uses, see the [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module.

`secrets.choice` is available to replace `random.choice`.

Alternatively you could also use `os.urandom` and map it to your set of characters with a modulus function, though you have to make sure that 0 to 255 modulus your set of characters distributes evenly.

**Comment by ZigaoWang** [comment]
Thank you for your kind suggestion! I already fixed it! This is a tiny Python test code, so it is not an actual project. But thanks anyway!
